/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef increment_CONSTANTS_H
#define increment_CONSTANTS_H

#include "increment_types.h"

namespace test {

class incrementConstants {
 public:
  incrementConstants();

};

extern const incrementConstants g_increment_constants;

} // namespace

#endif
