/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "increment_constants.h"

namespace test {

const incrementConstants g_increment_constants;

incrementConstants::incrementConstants() {
}

} // namespace

