/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mars_CONSTANTS_H
#define mars_CONSTANTS_H

#include "mars_types.h"

namespace MARS {

class marsConstants {
 public:
  marsConstants();

};

extern const marsConstants g_mars_constants;

} // namespace

#endif
