/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mars_constants.h"

namespace MARS {

const marsConstants g_mars_constants;

marsConstants::marsConstants() {
}

} // namespace

