//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

MARS.MARS_getCode_args = function(args) {
};
MARS.MARS_getCode_args.prototype = {};
MARS.MARS_getCode_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_getCode_args.prototype.write = function(output) {
  output.writeStructBegin('MARS_getCode_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_getCode_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new MARS.Code(args.success);
    }
  }
};
MARS.MARS_getCode_result.prototype = {};
MARS.MARS_getCode_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new MARS.Code();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_getCode_result.prototype.write = function(output) {
  output.writeStructBegin('MARS_getCode_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_sendMessage_args = function(args) {
};
MARS.MARS_sendMessage_args.prototype = {};
MARS.MARS_sendMessage_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_sendMessage_args.prototype.write = function(output) {
  output.writeStructBegin('MARS_sendMessage_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_sendMessage_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
MARS.MARS_sendMessage_result.prototype = {};
MARS.MARS_sendMessage_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_sendMessage_result.prototype.write = function(output) {
  output.writeStructBegin('MARS_sendMessage_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_getMessage_args = function(args) {
  this.message = null;
  if (args) {
    if (args.message !== undefined && args.message !== null) {
      this.message = args.message;
    }
  }
};
MARS.MARS_getMessage_args.prototype = {};
MARS.MARS_getMessage_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.message = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_getMessage_args.prototype.write = function(output) {
  output.writeStructBegin('MARS_getMessage_args');
  if (this.message !== null && this.message !== undefined) {
    output.writeFieldBegin('message', Thrift.Type.STRING, 1);
    output.writeString(this.message);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_getMessage_result = function(args) {
};
MARS.MARS_getMessage_result.prototype = {};
MARS.MARS_getMessage_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_getMessage_result.prototype.write = function(output) {
  output.writeStructBegin('MARS_getMessage_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_receiveFromJS_args = function(args) {
  this.c = null;
  if (args) {
    if (args.c !== undefined && args.c !== null) {
      this.c = new MARS.Code(args.c);
    }
  }
};
MARS.MARS_receiveFromJS_args.prototype = {};
MARS.MARS_receiveFromJS_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.c = new MARS.Code();
        this.c.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_receiveFromJS_args.prototype.write = function(output) {
  output.writeStructBegin('MARS_receiveFromJS_args');
  if (this.c !== null && this.c !== undefined) {
    output.writeFieldBegin('c', Thrift.Type.STRUCT, 1);
    this.c.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_receiveFromJS_result = function(args) {
};
MARS.MARS_receiveFromJS_result.prototype = {};
MARS.MARS_receiveFromJS_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_receiveFromJS_result.prototype.write = function(output) {
  output.writeStructBegin('MARS_receiveFromJS_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_getGameInfo_args = function(args) {
};
MARS.MARS_getGameInfo_args.prototype = {};
MARS.MARS_getGameInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_getGameInfo_args.prototype.write = function(output) {
  output.writeStructBegin('MARS_getGameInfo_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_getGameInfo_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new MARS.GameInfo(args.success);
    }
  }
};
MARS.MARS_getGameInfo_result.prototype = {};
MARS.MARS_getGameInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new MARS.GameInfo();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_getGameInfo_result.prototype.write = function(output) {
  output.writeStructBegin('MARS_getGameInfo_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_setGameInfo_args = function(args) {
  this.gameInfo = null;
  if (args) {
    if (args.gameInfo !== undefined && args.gameInfo !== null) {
      this.gameInfo = new MARS.GameInfo(args.gameInfo);
    }
  }
};
MARS.MARS_setGameInfo_args.prototype = {};
MARS.MARS_setGameInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameInfo = new MARS.GameInfo();
        this.gameInfo.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_setGameInfo_args.prototype.write = function(output) {
  output.writeStructBegin('MARS_setGameInfo_args');
  if (this.gameInfo !== null && this.gameInfo !== undefined) {
    output.writeFieldBegin('gameInfo', Thrift.Type.STRUCT, 1);
    this.gameInfo.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARS_setGameInfo_result = function(args) {
};
MARS.MARS_setGameInfo_result.prototype = {};
MARS.MARS_setGameInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

MARS.MARS_setGameInfo_result.prototype.write = function(output) {
  output.writeStructBegin('MARS_setGameInfo_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

MARS.MARSClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
MARS.MARSClient.prototype = {};
MARS.MARSClient.prototype.getCode = function(callback) {
  if (callback === undefined) {
    this.send_getCode();
    return this.recv_getCode();
  } else {
    var postData = this.send_getCode(true);
    return this.output.getTransport()
      .jqRequest(this, postData, arguments, this.recv_getCode);
  }
};

MARS.MARSClient.prototype.send_getCode = function(callback) {
  this.output.writeMessageBegin('getCode', Thrift.MessageType.CALL, this.seqid);
  var args = new MARS.MARS_getCode_args();
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush(callback);
};

MARS.MARSClient.prototype.recv_getCode = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new MARS.MARS_getCode_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getCode failed: unknown result';
};
MARS.MARSClient.prototype.sendMessage = function(callback) {
  if (callback === undefined) {
    this.send_sendMessage();
    return this.recv_sendMessage();
  } else {
    var postData = this.send_sendMessage(true);
    return this.output.getTransport()
      .jqRequest(this, postData, arguments, this.recv_sendMessage);
  }
};

MARS.MARSClient.prototype.send_sendMessage = function(callback) {
  this.output.writeMessageBegin('sendMessage', Thrift.MessageType.CALL, this.seqid);
  var args = new MARS.MARS_sendMessage_args();
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush(callback);
};

MARS.MARSClient.prototype.recv_sendMessage = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new MARS.MARS_sendMessage_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'sendMessage failed: unknown result';
};
MARS.MARSClient.prototype.getMessage = function(message, callback) {
  if (callback === undefined) {
    this.send_getMessage(message);
    this.recv_getMessage();
  } else {
    var postData = this.send_getMessage(message, true);
    return this.output.getTransport()
      .jqRequest(this, postData, arguments, this.recv_getMessage);
  }
};

MARS.MARSClient.prototype.send_getMessage = function(message, callback) {
  this.output.writeMessageBegin('getMessage', Thrift.MessageType.CALL, this.seqid);
  var args = new MARS.MARS_getMessage_args();
  args.message = message;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush(callback);
};

MARS.MARSClient.prototype.recv_getMessage = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new MARS.MARS_getMessage_result();
  result.read(this.input);
  this.input.readMessageEnd();

  return;
};
MARS.MARSClient.prototype.receiveFromJS = function(c, callback) {
  if (callback === undefined) {
    this.send_receiveFromJS(c);
    this.recv_receiveFromJS();
  } else {
    var postData = this.send_receiveFromJS(c, true);
    return this.output.getTransport()
      .jqRequest(this, postData, arguments, this.recv_receiveFromJS);
  }
};

MARS.MARSClient.prototype.send_receiveFromJS = function(c, callback) {
  this.output.writeMessageBegin('receiveFromJS', Thrift.MessageType.CALL, this.seqid);
  var args = new MARS.MARS_receiveFromJS_args();
  args.c = c;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush(callback);
};

MARS.MARSClient.prototype.recv_receiveFromJS = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new MARS.MARS_receiveFromJS_result();
  result.read(this.input);
  this.input.readMessageEnd();

  return;
};
MARS.MARSClient.prototype.getGameInfo = function(callback) {
  if (callback === undefined) {
    this.send_getGameInfo();
    return this.recv_getGameInfo();
  } else {
    var postData = this.send_getGameInfo(true);
    return this.output.getTransport()
      .jqRequest(this, postData, arguments, this.recv_getGameInfo);
  }
};

MARS.MARSClient.prototype.send_getGameInfo = function(callback) {
  this.output.writeMessageBegin('getGameInfo', Thrift.MessageType.CALL, this.seqid);
  var args = new MARS.MARS_getGameInfo_args();
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush(callback);
};

MARS.MARSClient.prototype.recv_getGameInfo = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new MARS.MARS_getGameInfo_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getGameInfo failed: unknown result';
};
MARS.MARSClient.prototype.setGameInfo = function(gameInfo, callback) {
  if (callback === undefined) {
    this.send_setGameInfo(gameInfo);
    this.recv_setGameInfo();
  } else {
    var postData = this.send_setGameInfo(gameInfo, true);
    return this.output.getTransport()
      .jqRequest(this, postData, arguments, this.recv_setGameInfo);
  }
};

MARS.MARSClient.prototype.send_setGameInfo = function(gameInfo, callback) {
  this.output.writeMessageBegin('setGameInfo', Thrift.MessageType.CALL, this.seqid);
  var args = new MARS.MARS_setGameInfo_args();
  args.gameInfo = gameInfo;
  args.write(this.output);
  this.output.writeMessageEnd();
  return this.output.getTransport().flush(callback);
};

MARS.MARSClient.prototype.recv_setGameInfo = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new MARS.MARS_setGameInfo_result();
  result.read(this.input);
  this.input.readMessageEnd();

  return;
};
